### PR TITLE
Recommendation/smi

### PR DESCRIPTION
**Pull request by caniszczyk**

### CODE REVIEW

**Comment by amye** [comment]
Things to change: 
1) This could use a recommendation for inclusion, I'm assuming that the answer is yes? But written down would be good. 
2) What's this note about KEDA in here?

**Comment by leecalcote** [comment]
@amye good comments. The answer to both of which is that the state of the recommendation is an incomplete draft, _almost_ ready for review.

**Comment by amye** [comment]
Checking in on this, looks like it's just needing the Project Scope, and recommendations for inclusion: sandbox, incubating?

**Comment by caniszczyk** [comment]
Hey @leecalcote please merge when the rec is ready and comment on the SMI TOC PR :)

**Pull request merged**
